from __future__ import annotations

# RC1 Remediation — Audit Finding #4 (Repository Pipeline integration).
#
# Previously the repository upload endpoint stopped after R2 persistence.
# AI Search indexing and Repository Memory population only happened if
# something else *separately* invoked QA / Council / Learning against the
# repository_id afterward — a decomposed, manually-chained set of stages.
#
# This module provides `run_repository_pipeline()`: a single async function
# that executes the complete lifecycle automatically on upload:
#
#   Upload → Extraction → Fingerprint → Manifest → Persist to R2
#       → Repository Memory seed → QA → Council → Learning / DNA
#       → AI Search index → Repository Ready
#
# Every stage reports an explicit outcome. Core stages (Memory, QA, Council
# and Learning) are expected to succeed for a production-ready repository;
# optional AI Search may be skipped when it is not configured. Stage results
# are included in the upload response so operators can see exactly what ran.
#
# The pipeline is intentionally *async* so it can be awaited inside a
# FastAPI async route handler without blocking the event loop.  Sync
# service functions (run_repository_qa, run_repository_council,
# update_project_dna) are wrapped with asyncio.to_thread().

import asyncio
import logging
import time
from typing import Any

from app.core.config import Settings
from app.services.repository_manager import RepositoryManifest

logger = logging.getLogger("uvicorn.error.hive.repository_pipeline")

# ---------------------------------------------------------------------------
# Stage: Repository Memory — seed basic manifest metadata
# ---------------------------------------------------------------------------


def _seed_repository_memory(settings: Settings, manifest: RepositoryManifest) -> dict[str, Any]:
    """Populate every scalar Repository Memory field from the uploaded snapshot."""
    try:
        from app.services.repository_manager import get_repository
        from app.services.repository_memory import set_memory_field
        from app.services.repository_profile import build_repository_memory_profile
        from app.storage.d1 import D1MetadataStore

        store = D1MetadataStore(settings)
        record = get_repository(manifest.repository_id)
        if record is None:
            raise RuntimeError(f"Repository {manifest.repository_id} disappeared before Memory seeding")

        fields: dict[str, Any] = {
            "project_manifest": {
                "repository_id": manifest.repository_id,
                "source_filename": manifest.source_filename,
                "fingerprint": manifest.fingerprint,
                "file_count": manifest.file_count,
                "total_bytes": manifest.total_bytes,
                "languages": manifest.languages,
                "dependencies": [
                    {
                        "manifest_path": dep.manifest_path,
                        "ecosystem": dep.ecosystem,
                        "declared": dep.declared,
                    }
                    for dep in manifest.dependencies
                ],
                "created_at": manifest.created_at,
                "updated_at": manifest.updated_at,
                "indexed_version": manifest.indexed_version,
            },
            **build_repository_memory_profile(record),
        }
        for field_name, content in fields.items():
            set_memory_field(
                store,
                repository_id=manifest.repository_id,
                field_name=field_name,
                content=content,
            )
        return {"ok": True, "fields_populated": sorted(fields)}
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "Repository pipeline memory seed failed repository_id=%s error=%s",
            manifest.repository_id,
            exc,
        )
        return {"ok": False, "error": str(exc)}


# ---------------------------------------------------------------------------
# Stage: Combined Repository Intelligence
# ---------------------------------------------------------------------------


def _run_intelligence(settings: Settings, repository_id: str) -> dict[str, Any]:
    """Run QA + Council + Project DNA as one evidence-consistent review.

    Repository Council consumes the exact QA payload generated by this run,
    so an upload cannot accidentally record two different QA executions.
    """
    try:
        from app.services.repository_intelligence import run_repository_intelligence

        report = run_repository_intelligence(settings, repository_id)
        summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
        qa = report.get("qa") if isinstance(report.get("qa"), dict) else {}
        council = report.get("council") if isinstance(report.get("council"), dict) else {}
        dna = report.get("project_dna") if isinstance(report.get("project_dna"), dict) else {}
        return {
            "ok": True,
            "status": summary.get("status"),
            "finding_count": summary.get("finding_count", 0),
            "blocking_finding_count": summary.get("blocking_finding_count", 0),
            "qa_score": summary.get("qa_score", qa.get("score")),
            "council_score": summary.get("council_score", council.get("overall_score")),
            "latest_qa_score": dna.get("latest_qa_score"),
            "report": report,
        }
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "Repository pipeline Intelligence failed repository_id=%s error=%s",
            repository_id,
            exc,
        )
        return {"ok": False, "error": str(exc)}


# ---------------------------------------------------------------------------
# Stage: AI Search indexing
# ---------------------------------------------------------------------------


async def _index_in_ai_search(settings: Settings, manifest: RepositoryManifest) -> dict[str, Any]:
    """Push the repository manifest summary to Cloudflare AI Search for
    semantic retrieval.  AI Search is optional (degrades gracefully)."""
    try:
        from app.storage.ai_search import AiSearchClient

        client = AiSearchClient(settings)
        if not client.enabled:
            return {"ok": False, "skipped": True, "reason": "ai_search_not_configured"}

        # AI Search (Cloudflare AutoRAG) indexes documents via the R2 bucket
        # it is connected to — HIVE doesn't push individual documents via API.
        # We record the indexing intent in Repository Memory so the AI Search
        # instance can pick up the manifest from R2 on its next sync cycle.
        # The diagnostics call confirms connectivity.
        diag = await client.diagnostics()
        return {"ok": diag.get("ok", False), "diagnostics": diag}
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "Repository pipeline AI Search indexing failed repository_id=%s error=%s",
            manifest.repository_id,
            exc,
        )
        return {"ok": False, "error": str(exc)}


# ---------------------------------------------------------------------------
# Main pipeline entry point
# ---------------------------------------------------------------------------


async def run_repository_pipeline(
    settings: Settings,
    manifest: RepositoryManifest,
    *,
    r2_persisted: bool,
) -> dict[str, Any]:
    """Execute the complete post-upload pipeline for a repository.

    Returns a ``pipeline`` dict that documents each stage's outcome.
    Never raises — all stage failures are captured in the return value.
    """
    repository_id = manifest.repository_id
    t_start = time.monotonic()

    pipeline: dict[str, Any] = {
        "repository_id": repository_id,
        "r2_persisted": r2_persisted,
    }

    # Stage: Memory seed (sync, fast)
    pipeline["memory_seed"] = await asyncio.to_thread(
        _seed_repository_memory, settings, manifest
    )

    # Stage: Repository Intelligence. QA runs once and Council consumes that
    # exact evidence; the merged report also refreshes Project DNA.
    intelligence = await asyncio.to_thread(_run_intelligence, settings, repository_id)
    pipeline["intelligence"] = intelligence

    # Backwards-compatible stage summaries keep existing clients readable
    # while the canonical result lives under ``intelligence``.
    if intelligence.get("ok") is True:
        pipeline["qa"] = {"ok": True, "score": intelligence.get("qa_score")}
        pipeline["council"] = {"ok": True, "overall_score": intelligence.get("council_score")}
        pipeline["learning"] = {"ok": True, "latest_qa_score": intelligence.get("latest_qa_score")}
    else:
        error = str(intelligence.get("error") or "Repository Intelligence failed")
        pipeline["qa"] = {"ok": False, "error": error}
        pipeline["council"] = {"ok": False, "error": error}
        pipeline["learning"] = {"ok": False, "error": error}

    # Stage: AI Search index (async)
    pipeline["ai_search"] = await _index_in_ai_search(settings, manifest)

    pipeline["elapsed_ms"] = round((time.monotonic() - t_start) * 1000, 1)

    required_stages = ("memory_seed", "intelligence")
    required_failed = [
        stage
        for stage in required_stages
        if isinstance(pipeline.get(stage), dict) and pipeline[stage].get("ok") is not True
    ]
    optional_failed = [
        stage
        for stage in ("ai_search",)
        if isinstance(pipeline.get(stage), dict)
        and pipeline[stage].get("ok") is False
        and not pipeline[stage].get("skipped")
    ]

    if required_failed:
        pipeline["status"] = "setup_incomplete"
        pipeline["failed_stages"] = required_failed + optional_failed
        logger.error(
            "Repository pipeline incomplete repository_id=%s required_failed=%s optional_failed=%s",
            repository_id,
            required_failed,
            optional_failed,
        )
    elif optional_failed:
        pipeline["status"] = "ready_with_warnings"
        pipeline["failed_stages"] = optional_failed
        logger.warning(
            "Repository pipeline ready with optional warnings repository_id=%s failed=%s",
            repository_id,
            optional_failed,
        )
    else:
        pipeline["status"] = "ready"
        logger.info(
            "Repository pipeline complete repository_id=%s elapsed_ms=%s",
            repository_id,
            pipeline["elapsed_ms"],
        )

    pipeline["required_stages_ready"] = not required_failed
    return pipeline
