from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.core.config import Settings
from app.services.repository_manager import RepositoryManagerError, get_repository
from app.services.repository_memory import append_history_entry, get_memory_field
from app.services.repository_qa import run_repository_qa
from app.storage.d1 import D1MetadataStore

# Phase 8 - Repository Council.
#
# HONESTY NOTE: "performance" and "ai_generated_code" dimensions below are
# genuine heuristic placeholders, not measured signal — there is no runtime
# profiling data or a trained AI-code classifier available here. They are
# included because the programme spec calls for these review dimensions,
# but scores on those two axes should be read as low-confidence until a
# real data source is wired in (see each function's docstring).

DIMENSIONS: tuple[str, ...] = (
    "architecture",
    "documentation",
    "dependencies",
    "technical_debt",
    "security",
    "performance",
    "maintainability",
    "ai_generated_code",
    "repository_health",
)

DEFAULT_COUNCIL_WEIGHTS: dict[str, float] = {
    "architecture": 0.15,
    "documentation": 0.10,
    "dependencies": 0.10,
    "technical_debt": 0.15,
    "security": 0.20,
    "performance": 0.05,
    "maintainability": 0.15,
    "ai_generated_code": 0.03,
    "repository_health": 0.07,
}

_AI_GENERATED_MARKERS = re.compile(
    r"(?i)(generated by (chatgpt|copilot|claude|gpt-)|ai[- ]generated|auto-generated by)"
)


@dataclass(frozen=True)
class CouncilDimensionScore:
    dimension: str
    score: float
    rationale: str


@dataclass(frozen=True)
class CouncilReport:
    repository_id: str
    occurred_at: str
    overall_score: float
    dimensions: list[CouncilDimensionScore]
    recommendations: list[str]

    def public_payload(self) -> dict[str, Any]:
        return {
            "repository_id": self.repository_id,
            "occurred_at": self.occurred_at,
            "overall_score": self.overall_score,
            "dimensions": [asdict(d) for d in self.dimensions],
            "recommendations": self.recommendations,
        }


def _score_from_qa(qa_payload: dict[str, Any], check_names: tuple[str, ...]) -> float:
    checks = {c["name"]: c for c in qa_payload["checks"]}
    relevant = [checks[name] for name in check_names if name in checks]
    if not relevant:
        return 0.5
    return sum(1.0 if c["status"] == "ok" else 0.0 for c in relevant) / len(relevant)


def _documentation_score(root: Path) -> tuple[float, str]:
    has_readme = any((root / name).exists() for name in ("README.md", "README.rst", "README.txt"))
    has_docs_dir = (root / "docs").exists()
    score = (0.6 if has_readme else 0.0) + (0.4 if has_docs_dir else 0.0)
    return score, f"README present={has_readme}, docs/ present={has_docs_dir}"


def _ai_generated_code_score(root: Path) -> tuple[float, str]:
    """Heuristic only: greps for a small set of common AI-attribution
    comment markers. Absence of markers does NOT mean the code wasn't
    AI-generated — most AI-assisted code carries no such marker at all.
    This is a low-confidence placeholder pending a real classifier."""
    marker_hits = 0
    scanned = 0
    for path in root.rglob("*.py"):
        if scanned >= 500:
            break
        scanned += 1
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if _AI_GENERATED_MARKERS.search(text):
            marker_hits += 1
    # Presence of explicit attribution markers is treated as neutral-to-good
    # (transparent) rather than penalised; this dimension mainly exists as a
    # placeholder for a future real signal.
    return 1.0, f"{marker_hits} file(s) with explicit AI-attribution markers out of {scanned} scanned (low-confidence heuristic)"


def _performance_score(qa_payload: dict[str, Any]) -> tuple[float, str]:
    """Heuristic placeholder: no runtime profiling data is available for an
    uploaded repository, so this maps directly from the dead-code/orphan
    signal already computed by Repository QA as a very rough proxy for
    'bloat', not actual performance."""
    checks = {c["name"]: c for c in qa_payload["checks"]}
    dead_code = checks.get("dead_code_detection", {})
    flagged = (
        dead_code.get("details", {}).get("duplicate_content_group_count", 0)
        + dead_code.get("details", {}).get("orphan_candidate_count", 0)
    )
    score = 1.0 if flagged == 0 else max(0.3, 1.0 - min(flagged, 10) / 10)
    return score, f"proxy score from {flagged} duplicate/orphan item(s) (no real profiling data available)"


def _recommendations_for(dimensions: list[CouncilDimensionScore]) -> list[str]:
    recommendations = []
    for dimension in dimensions:
        if dimension.score < 0.6:
            recommendations.append(f"Improve {dimension.dimension.replace('_', ' ')}: {dimension.rationale}")
    return recommendations


def run_repository_council(
    settings: Settings, repository_id: str, *, weights: dict[str, float] | None = None
) -> CouncilReport:
    record = get_repository(repository_id)
    if record is None:
        raise RepositoryManagerError(f"Unknown repository_id: {repository_id}")

    qa_report = run_repository_qa(repository_id)
    qa_payload = qa_report.public_payload()
    root = record.workdir

    documentation_score, documentation_rationale = _documentation_score(root)
    ai_generated_score, ai_generated_rationale = _ai_generated_code_score(root)
    performance_score, performance_rationale = _performance_score(qa_payload)

    dimensions = [
        CouncilDimensionScore(
            "architecture",
            _score_from_qa(qa_payload, ("architecture_validation",)),
            "Derived from Repository QA architecture_validation check",
        ),
        CouncilDimensionScore("documentation", documentation_score, documentation_rationale),
        CouncilDimensionScore(
            "dependencies",
            _score_from_qa(qa_payload, ("dependency_validation",)),
            "Derived from Repository QA dependency_validation check",
        ),
        CouncilDimensionScore(
            "technical_debt",
            _score_from_qa(qa_payload, ("dead_code_detection",)),
            "Derived from Repository QA dead_code_detection check",
        ),
        CouncilDimensionScore(
            "security",
            _score_from_qa(qa_payload, ("security_scanning",)),
            "Derived from Repository QA security_scanning check",
        ),
        CouncilDimensionScore("performance", performance_score, performance_rationale),
        CouncilDimensionScore(
            "maintainability",
            _score_from_qa(qa_payload, ("lint", "type_checking", "import_validation")),
            "Derived from Repository QA lint/type_checking/import_validation checks",
        ),
        CouncilDimensionScore("ai_generated_code", ai_generated_score, ai_generated_rationale),
        CouncilDimensionScore("repository_health", qa_payload["score"], "Overall Repository QA score"),
    ]

    resolved_weights = weights or DEFAULT_COUNCIL_WEIGHTS
    total_weight = sum(max(0.0, resolved_weights.get(d.dimension, 0.0)) for d in dimensions) or 1.0
    overall = sum(d.score * max(0.0, resolved_weights.get(d.dimension, 0.0)) for d in dimensions) / total_weight

    return CouncilReport(
        repository_id=repository_id,
        occurred_at=datetime.now(UTC).isoformat(),
        overall_score=round(overall, 3),
        dimensions=dimensions,
        recommendations=_recommendations_for(dimensions),
    )


def run_and_record_council(
    settings: Settings, repository_id: str, *, weights: dict[str, float] | None = None
) -> CouncilReport:
    report = run_repository_council(settings, repository_id, weights=weights)
    store = D1MetadataStore(settings)
    append_history_entry(
        store,
        repository_id=repository_id,
        field_name="repository_council_history",
        entry=report.public_payload(),
    )
    return report


def get_council_history(settings: Settings, repository_id: str) -> list[dict[str, Any]]:
    store = D1MetadataStore(settings)
    field = get_memory_field(store, repository_id=repository_id, field_name="repository_council_history")
    return list(field.content) if field and field.content else []
